/*Escreva os seguintes comandos relacionados com Sequences no MariaDB 10.3. 
    CREATE SEQUENCE s START WITH 100 INCREMENT BY 10; 
    CREATE SEQUENCE s2 START WITH -100 INCREMENT BY -10; 
    CREATE SEQUENCE s3 START WITH -100 INCREMENT BY 10 MINVALUE=-100 MAXVALUE=1000;
Execute:

    SELECT NEXTVAL(s); 
    SELECT NEXTVAL(s); 
    SELECT NEXTVAL(s);
Teste também para s2 e s3;
*/

CREATE SEQUENCE s START WITH 100 INCREMENT BY 10;
SELECT NEXTVAL('s');
SELECT NEXTVAL('s');
SELECT NEXTVAL('s');

CREATE SEQUENCE s2 START WITH -100 INCREMENT BY -10;
SELECT NEXTVAL('s2');
SELECT NEXTVAL('s2');
SELECT NEXTVAL('s2');

CREATE SEQUENCE s3 START WITH -100 INCREMENT BY 10 MINVALUE -100 MAXVALUE 1000;
SELECT NEXTVAL('s3');
SELECT NEXTVAL('s3');
SELECT NEXTVAL('s3');
